services:
  reservations-service:
    build: .
    env_file: .env
    ports:
      - "4002:4002"
    restart: always
    depends_on:
      - postgres
    networks:
      - usp-net

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASS}"
      POSTGRES_DB: "${DATABASE_NAME}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - usp-net

volumes:
  pgdata:

networks:
  usp-net: