services:
  ingestion-service:
    build: .
    env_file: .env
    restart: always
    depends_on:
      - postgres
    networks:
      - usp-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file: .env
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - "5675:5672"
      - "15675:15672"
    restart: always
    networks:
      - usp-net

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASS}"
      POSTGRES_DB: "${DATABASE_NAME}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - usp-net

volumes:
  pgdata:
  rabbitmqdata:

networks:
  usp-net: